/**
 * NexLoad Cookie Exporter — popup.js
 * Exports YouTube cookies in Netscape/Mozilla format for yt-dlp
 * Uploads directly to NexLoad server — no need to open the website
 */

const SERVER_URL = "https://nexload-ifas.onrender.com";

function showToast(msg, isError) {
  const t = document.getElementById("toast");
  t.textContent = msg;
  t.style.background = isError ? "#ef4444" : "#1a1a1a";
  t.classList.add("show");
  setTimeout(() => t.classList.remove("show"), 3000);
}

function setCookieStatus(active, count) {
  const dot = document.getElementById("statusDot");
  const text = document.getElementById("statusText");
  dot.className = "status-dot " + (active ? "active" : "inactive");
  if (active) {
    text.innerHTML = `<strong>${count} cookie${count > 1 ? "s" : ""} found</strong> — ready to export`;
  } else {
    text.innerHTML = "<strong>No YouTube cookies</strong> — log into YouTube first";
  }
}

async function getYoutubeCookies() {
  const domains = [
    "youtube.com",
    ".youtube.com",
    "www.youtube.com",
    "accounts.google.com",
    ".google.com",
    "google.com",
  ];

  const allCookies = new Map();

  for (const domain of domains) {
    try {
      const cookies = await chrome.cookies.getAll({ domain });
      for (const c of cookies) {
        const key = `${c.domain}|${c.name}|${c.path}`;
        allCookies.set(key, c);
      }
    } catch (e) {
      console.warn(`Failed to get cookies for ${domain}:`, e);
    }
  }

  return Array.from(allCookies.values());
}

function cookieToNetscape(c) {
  const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
  const flag = domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = c.secure ? "TRUE" : "FALSE";
  const expires = c.expirationDate ? Math.floor(c.expirationDate) : 0;
  return `${domain}\t${flag}\t${c.path}\t${secure}\t${expires}\t${c.name}\t${c.value}`;
}

function buildCookieFile(cookies) {
  const deduped = new Map();
  for (const c of cookies) {
    const key = `${c.domain}|${c.name}|${c.path}`;
    deduped.set(key, c);
  }
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by NexLoad Cookie Exporter",
    "# https://github.com/abir2afridi/NexLoad",
    "",
  ];
  for (const c of deduped.values()) {
    lines.push(cookieToNetscape(c));
  }
  return lines.join("\n");
}

function downloadFile(content, filename) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Init ───
(async () => {
  const statusText = document.getElementById("statusText");
  const exportBtn = document.getElementById("exportBtn");
  const uploadBtn = document.getElementById("uploadBtn");

  try {
    statusText.innerHTML = "Checking cookies...";
    const cookies = await getYoutubeCookies();
    setCookieStatus(cookies.length > 0, cookies.length);

    // Export button — download .txt file
    exportBtn.addEventListener("click", () => {
      if (cookies.length === 0) {
        showToast("No cookies found — log into YouTube first", true);
        return;
      }
      const file = buildCookieFile(cookies);
      downloadFile(file, "cookies.txt");
      showToast(`cookies.txt downloaded (${cookies.length} cookies)`);
    });

    // Upload button — directly POST to NexLoad server
    uploadBtn.addEventListener("click", async () => {
      if (cookies.length === 0) {
        showToast("No cookies found — log into YouTube first", true);
        return;
      }

      uploadBtn.disabled = true;
      uploadBtn.innerHTML = `
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="spin">
          <circle cx="12" cy="12" r="10" stroke-dasharray="50" stroke-dashoffset="20"/>
        </svg>
        Uploading...
      `;

      const file = buildCookieFile(cookies);

      try {
        const res = await fetch(`${SERVER_URL}/api/cookies`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ cookies: file }),
        });

        const data = await res.json();

        if (res.ok) {
          showToast("Cookies uploaded! YouTube downloads enabled.");
        } else {
          showToast("Upload failed: " + (data.error || "Unknown error"), true);
        }
      } catch (e) {
        showToast("Server unreachable — try again later", true);
        console.error("Upload failed:", e);
      } finally {
        uploadBtn.disabled = false;
        uploadBtn.innerHTML = `
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
            <polyline points="17 8 12 3 7 8"/>
            <line x1="12" y1="3" x2="12" y2="15"/>
          </svg>
          Upload to NexLoad
        `;
      }
    });
  } catch (err) {
    setCookieStatus(false, 0);
    statusText.innerHTML = `<strong>Permission error</strong> — ${err.message}`;
    exportBtn.disabled = true;
    uploadBtn.disabled = true;
    showToast("Cookie permission denied", true);
    console.error("NexLoad extension error:", err);
  }
})();
